### ISSUE TITLE
[Issue] World corruption? Fastcraft Issues?

### ISSUE THREAD

**Issue by accessdenied0** [TeamMetallurgy/MetallurgyChisel#1]
Hello @Shadowclaimer @Glassmaker ,

Recently installed your mod to my world. In the moment I tried to load this world in SSP I got the message: "level.dat already has been uses [...] Do you want make a backup [...]". After loading up I got this crash: http://pastebin.com/L2XTK3Xm . This crash doesn't say much because so far I can see this my world blocks just got scrambled... After creating a new world: http://pastebin.com/yFPBwCCV .
Then I disabled this mod and tried to load the world again, didn't worked sadly...

Which Forge requirements? I got a similar problem here: https://github.com/HenryLoenwind/EnderIOAddons/issues/1
here seems to be the Forge version.

access_denied

**Comment by Shadowclaimer** [comment]
@Glassmaker

**Comment by Glassmaker** [comment]
HI @accessdenied0 

Looks like something went wrong with forge's block mapping, you can see the in the first crash it's trying to use fluxedCrystals tile entity on translocator's tile entity.

The second crash is weird, we don't add loot to dungeon chests at the moment.

MetallurgyChisel is built with forge 1448, but I think it would be fine till forge 1291.

Can you try a new world and see if it works with every mod enabled?

**Comment by Glassmaker** [comment]
I think we can rule out fastcraft, just tested it on an old world and a new one forge 1448, no crashing.

**Comment by accessdenied0** [comment]
Hey @Glassmaker,

I thank you a lot for your help, as you might see I have a lot of mods in my pack and I experience this issue with every new mod I have added: This one, EnderIO-Addons and OC-Cards. I got to sort some mods out but It is strange... Is there a problem with Java 8 or the version of Chisel I use? (Currently I use _"Chisel 2"_ but there is also _"Chisel 2 - A new hope"_ ...)

access_denied

**Comment by Glassmaker** [comment]
@accessdenied0 not that I know of, chisel 2 and chisel new hope are running fine over on Java 8

**Comment by accessdenied0** [comment]
@Glassmaker,

I put some mod out of my pack and I think I can restrict the trouble maker to: RFQuarries and AncientWarfare but because I used AW much longer and didn't had any trouble with it I think it is RFQuarries... Can't quite tell why it didn't worked but now It seems to work (A world is created and I can do stuff and things).

I thank you a lot for your help, and sorry for any trouble.

access_denied

**Comment by Glassmaker** [comment]
You're welcome, and don't worry about it. :)

Closing the issue :)
